/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ScalarProduct */

#ifndef _Included_com_example_ScalarProduct
#define _Included_com_example_ScalarProduct
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ScalarProduct
 * Method:    multi01
 * Signature: ([Ljava/lang/Double;[Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_com_example_ScalarProduct_multi01
  (JNIEnv *, jobject, jobjectArray, jobjectArray);

/*
 * Class:     com_example_ScalarProduct
 * Method:    multi02
 * Signature: ([Ljava/lang/Double;)Ljava/lang/Double;
 */
JNIEXPORT jobject JNICALL Java_com_example_ScalarProduct_multi02
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     com_example_ScalarProduct
 * Method:    multi03
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ScalarProduct_multi03
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
